"""Add ClassTypeProject tables

Revision ID: 661574a4ea4d
Revises: bb58295c3cb8
Create Date: 2026-04-25 09:51:27.969582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '661574a4ea4d'
down_revision: Union[str, Sequence[str], None] = 'bb58295c3cb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name_ru', sa.String(length=255), nullable=False),
    sa.Column('name_eng', sa.String(length=255), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name_eng', name='uq_project_class_name_eng'),
    sa.UniqueConstraint('project_id', 'name_ru', name='uq_project_class_name_ru')
    )
    op.alter_column('annotations', 'class_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.add_column('images', sa.Column('user_id', sa.UUID(), nullable=False))
    op.add_column('images', sa.Column('project_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'images', 'projects', ['project_id'], ['id'])
    op.create_foreign_key(None, 'images', 'users', ['user_id'], ['id'])
    op.add_column('masks', sa.Column('class_name', sa.String(length=200), nullable=False))
    op.create_unique_constraint('uq_oauth_provider_user', 'oauth_accounts', ['provider', 'provider_user_id'])
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'users', ['definition_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('uq_oauth_provider_user', 'oauth_accounts', type_='unique')
    op.drop_column('masks', 'class_name')
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.drop_column('images', 'project_id')
    op.drop_column('images', 'user_id')
    op.alter_column('annotations', 'class_name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_table('class_types')
    # ### end Alembic commands ###
